Update sys-info to v0.9
rbtcollins/effective-limits.rs pull request #16
Opened 2021-05-17 19:30 UTC by Alovchin91

This PR updates sys-info dependency to v0.9 which improves Windows support to be arch-independent and enables building rustup for Windows on ARM64: https://github.com/rust-lang/rustup/issues/2612

This is a re-post of this PR: #14

2021-06-08 20:48 UTC, Alovchin91 commented
Omg, is this serious? 🤦 

> ```
> warning: c/windows.c: In function 'get_cpu_speed':
> warning: c/windows.c:71:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
> warning:   for (unsigned int i = 0; i < num; i++) {
> warning:   ^
> warning: c/windows.c:71:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
> ```

@rbtcollins Is it okay if I'll try to upgrade the version of mingw used for the CI to at least 6.3.0?

2021-06-08 21:09 UTC, Alovchin91 commented
Done! Seems to run on my fork. I've used the same mingw packages as [rustup](https://github.com/rust-lang/rustup/blob/master/.github/workflows/windows-builds-on-pr.yaml).

2021-06-08 21:11 UTC, Alovchin91 commented
But now it seems sys-info needs a cc-rs upgrade to [correctly find tools on Windows arm64](https://github.com/alexcrichton/cc-rs/pull/597) without the use of Dev Command line 🤔 Would you prefer me to close this PR and open a new one, or keep this one and open another one when sys-info merges the cc-rs update?

2021-06-13 11:22 UTC, kinnison approved these changes
This seems okay.

2021-06-13 11:27 UTC, kinnison requested changes
Actually I've just realied this is editing the workflow files directly rather than via the template, I'll fix that up.

2021-06-13 11:33 UTC, Alovchin91 commented
Oh, sorry, I didn't realize there was a template 😬 Thanks for fixing this up!

2021-06-13 11:34 UTC, kinnison approved these changes

2021-06-13 11:36 UTC, kinnison commented
@Alovchin91 Yeah this is borrowed from Rustup's CI, each file does have a comment like:

```
# This is ci/actions-templates/windows-builds-template.yaml
# Do not edit this file in .github/workflows
```

at the top, but that's easy to miss :/

2021-06-13 11:38 UTC, merged